server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: 395010

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: configserver:http://localhost:5555

okta:
  oauth2:
    issuer: https://dev-01778054.okta.com/oauth2/default
    audience: api://default