server:
  port: 8093

spring:
  data:
    mongodb:
      uri: mongodb+srv://rajchdvadiya:395010@cluster0.nie23.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0


  config:
    import: configserver:http://localhost:5555