server:
  port: 8093

spring:
  data:
    mongodb:
      uri: mongodb+srv://rajchdvadiya:395010@cluster0.nie23.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/